#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';
define('BASEPATH', __DIR__);
define("APPPATH", BASEPATH . "/app");
define("DATABASEPATH", BASEPATH . "/database");
define("CONFIGPATH", BASEPATH . "/config");
define("COREPATH", BASEPATH . "/core");
define("PUBLICPATH", BASEPATH . "/public");
define("ROUTESPATH", BASEPATH . "/routes");

use Jtech\Console\Kernel;

$app = new Kernel;
$app->run($argv);
